import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({children}: any) {
  return (
    <html lang="en">
      <body
      //  className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     <Header />
        {children}
     <Footer />
      </body>
    </html>
  );
}